name: Deploy Cloudflared Binaries to R2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 安装并配置 rclone
      - name: Install and Configure rclone
        run: |
          echo "Installing rclone..."
          curl https://rclone.org/install.sh | sudo bash
          
          echo "Creating rclone config directory..."
          mkdir -p ~/.config/rclone
          
          echo "Writing rclone config file..."
          echo "[myR2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" > ~/.config/rclone/rclone.conf

      # 步骤 3: 下载并上传 AMD64 架构的 Cloudflared
      - name: Download and Upload AMD64
        run: |
          echo "Downloading AMD64 version..."
          curl -L -o cloudflared-amd64 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          
          echo "Uploading AMD64 version..."
          rclone copyto cloudflared-amd64 myR2:gfw/cloudflared --s3-no-check-bucket --progress
          rclone copyto cloudflared-amd64 myR2:gfw/backend --s3-no-check-bucket --progress
          
          echo "Cleaning up..."
          rm cloudflared-amd64

      # 步骤 4: 下载并上传 ARM64 架构的 Cloudflared
        run: |
          echo "Downloading ARM64 version..."
          curl -L -o cloudflared-arm64 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64

          echo "Uploading ARM64 version..."
          rclone copyto cloudflared-arm64 myR2:gfw-arm/cloudflared --s3-no-check-bucket --progress
          rclone copyto cloudflared-arm64 myR2:gfw-arm/backend --s3-no-check-bucket --progress
          
          echo "Cleaning up..."
          rm cloudflared-arm64

      # 步骤 5: 刷新 Cloudflare 缓存
      - name: Purge Cloudflare Cache
        run: |
          echo "Purging Cloudflare cache..."
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{ 
                 "files": [
                   "https://amd.dogchild.eu.org/cloudflared",
                   "https://arm.dogchild.eu.org/cloudflared",
                   "https://amd.dogchild.eu.org/backend",
                   "https://arm.dogchild.eu.org/backend"
                 ]
               }'