name: Deploy Cloudflared Binaries to R2

# 手动触发
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools (UPX)
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl

      - name: Setup rclone
        uses: rclone/setup-rclone@v1
        with:
          rclone_config: |
            [myR2]
            type = s3
            provider = Cloudflare
            access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
            endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

      - name: Download, Compress, and Upload AMD64
        run: |
          echo "Processing AMD64 version..."
          curl -L -o cloudflared-linux-amd64 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          upx --best --lzma -o cloudflared-amd64-compressed cloudflared-linux-amd64
          echo "Uploading to gfw bucket..."
          rclone copyto cloudflared-amd64-compressed myR2:gfw/cloudflared --progress

      - name: Download, Compress, and Upload ARM64
        run: |
          echo "Processing ARM64 version..."
          curl -L -o cloudflared-linux-arm64 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64
          chmod +x cloudflared-linux-arm64
          upx --best --lzma -o cloudflared-arm64-compressed cloudflared-linux-arm64
          echo "Uploading to gfw-arm bucket..."
          rclone copyto cloudflared-arm64-compressed myR2:gfw-arm/cloudflared --progress

      - name: Purge Cloudflare Cache
        run: |
          echo "Purging Cloudflare cache..."
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{
                 "files": [
                   "https://amd.dogchild.eu.org/cloudflared",
                   "https://arm.dogchild.eu.org/cloudflared"
                 ]
               }'
