name: Deploy Xray Binaries to R2

# 手动触发
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools (UPX, Unzip)
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl unzip

      - name: Setup rclone
        uses: rclone/setup-rclone@v1
        with:
          rclone_config: |
            [myR2]
            type = s3
            provider = Cloudflare
            access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
            endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

      - name: Download, Compress, and Upload AMD64
        run: |
          echo "Processing AMD64 version..."
          curl -L -o xray-linux-64.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip xray-linux-64.zip xray
          upx --best --lzma -o xray-amd64-compressed xray
          echo "Uploading to gfw bucket..."
          rclone copyto xray-amd64-compressed myR2:gfw/xray --progress

      - name: Download, Compress, and Upload ARM64
        run: |
          echo "Processing ARM64 version..."
          curl -L -o xray-linux-arm64.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-arm64-v8a.zip
          unzip xray-linux-arm64.zip xray
          upx --best --lzma -o xray-arm64-compressed xray
          echo "Uploading to gfw-arm bucket..."
          rclone copyto xray-arm64-compressed myR2:gfw-arm/xray --progress
          
      - name: Purge Cloudflare Cache
        run: |
          echo "Purging Cloudflare cache..."
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{
                 "files": [
                   "https://amd.dogchild.eu.org/xray",
                   "https://arm.dogchild.eu.org/xray"
                 ]
               }'
